#!/bin/bash
DIR=$(dirname "$(realpath -s "$0")")
LIBS="$DIR/../../linux-x86/intel_clc/lib64"
BIN="$DIR/../../linux-x86/intel_clc/bin/intel_clc"

exec env LD_LIBRARY_PATH="$LIBS:$LD_LIBRARY_PATH" "$LIBS/ld-linux-x86-64.so.2" "$BIN" "$@"
